-- TalentZify — seed data for the content hub, career quiz, and daily challenge.
-- Run after 0001_init.sql and 0002_dashboard_and_share.sql. Safe to re-run
-- (clears and re-inserts).

delete from public.quiz_questions;
delete from public.content_items;
delete from public.challenge_questions;
delete from public.vocabulary_words;

-- ── content_items ───────────────────────────────────────────────────────
insert into public.content_items (title, description, type, category, url, thumbnail_url) values
('How to Pick a Stream After Class 10', 'Science, Commerce, or Arts? A practical framework for deciding, not just "what pays more".', 'article', 'career_guidance', 'https://www.example.com/pick-a-stream', null),
('What Does a Software Engineer Actually Do?', 'A day-in-the-life breakdown of the job, minus the LinkedIn buzzwords.', 'article', 'career_guidance', 'https://www.example.com/swe-day-in-life', null),
('Careers Beyond Engineering and Medicine', 'Design, product management, data science, UX research, and a dozen other paths Indian students rarely hear about.', 'article', 'career_guidance', 'https://www.example.com/beyond-engg-medicine', null),
('Free Coding Basics: Python in 2 Weeks', 'A structured, beginner-friendly roadmap to Python fundamentals with daily practice problems.', 'article', 'tech_skills', 'https://www.example.com/python-2-weeks', null),
('Intro to Git and GitHub for Beginners', 'Version control explained without the jargon: what it is, why it matters, and your first repository.', 'video', 'tech_skills', 'https://www.example.com/git-github-intro', null),
('Build Your First Website (HTML/CSS)', 'No prior experience needed. By the end you will have a live personal page.', 'video', 'tech_skills', 'https://www.example.com/first-website', null),
('What is Artificial Intelligence, Really?', 'Cutting through the hype: a clear, non-technical explanation of AI/ML for high schoolers.', 'article', 'tech_skills', 'https://www.example.com/what-is-ai', null),
('Writing a Resume With Zero Work Experience', 'How to present school projects, clubs, and volunteering like real accomplishments.', 'article', 'job_readiness', 'https://www.example.com/first-resume', null),
('Acing Your First Interview', 'Common questions, how to talk about yourself without rehearsing a script, and what interviewers actually notice.', 'video', 'job_readiness', 'https://www.example.com/first-interview', null),
('Internships You Can Actually Get in Class 11-12', 'Realistic internship and volunteering options for school students, and how to find them.', 'article', 'job_readiness', 'https://www.example.com/school-internships', null),
('Time Management for Students Who Do Too Much', 'A simple system for balancing school, exams, and side projects without burning out.', 'article', 'upskilling', 'https://www.example.com/time-management', null),
('Public Speaking Without the Panic', 'Practical exercises to get comfortable presenting in class, in interviews, and on camera.', 'video', 'upskilling', 'https://www.example.com/public-speaking', null),
('How to Learn Any New Skill Faster', 'The difference between passive learning and deliberate practice, explained with real study techniques.', 'article', 'upskilling', 'https://www.example.com/learn-faster', null),
('Understanding Competitive Exams: JEE, NEET, CUET', 'What each exam actually tests, how they differ, and how to decide which path fits you.', 'article', 'career_guidance', 'https://www.example.com/competitive-exams', null),
('Personal Finance Basics Before You Turn 18', 'Saving, budgeting, and understanding money before your first paycheck.', 'article', 'job_readiness', 'https://www.example.com/personal-finance-basics', null),
('Intro to Data: Spreadsheets to Dashboards', 'Excel/Sheets fundamentals that quietly power a huge number of real jobs.', 'video', 'tech_skills', 'https://www.example.com/intro-to-data', null);

-- ── quiz_questions ──────────────────────────────────────────────────────
-- `options[].streams` are informal tags used to tally suggested streams —
-- not a scientific psychometric model, just a lightweight starter signal.
insert into public.quiz_questions (question, options, "order") values
(
  'Which of these sounds most fun to spend a Saturday on?',
  '[
    {"label": "Building or fixing something with your hands or a computer", "streams": ["Engineering & Technology"]},
    {"label": "Debating an idea or writing about something you care about", "streams": ["Humanities & Media"]},
    {"label": "Organizing an event or leading a group project", "streams": ["Business & Management"]},
    {"label": "Helping someone solve a personal problem", "streams": ["Healthcare & Social Sciences"]}
  ]'::jsonb,
  1
),
(
  'In a group project, you naturally end up...',
  '[
    {"label": "Figuring out how things actually work under the hood", "streams": ["Engineering & Technology"]},
    {"label": "Making sure the story/presentation is clear and convincing", "streams": ["Humanities & Media"]},
    {"label": "Keeping everyone on track and managing the plan", "streams": ["Business & Management"]},
    {"label": "Checking that the outcome actually helps people", "streams": ["Healthcare & Social Sciences"]}
  ]'::jsonb,
  2
),
(
  'Which school subject do you look forward to most?',
  '[
    {"label": "Math or Computer Science", "streams": ["Engineering & Technology"]},
    {"label": "English, History, or Political Science", "streams": ["Humanities & Media"]},
    {"label": "Economics or Business Studies", "streams": ["Business & Management"]},
    {"label": "Biology", "streams": ["Healthcare & Social Sciences"]}
  ]'::jsonb,
  3
),
(
  'Pick a problem you would enjoy solving:',
  '[
    {"label": "Why does this app keep crashing?", "streams": ["Engineering & Technology"]},
    {"label": "Why did public opinion shift on this issue?", "streams": ["Humanities & Media"]},
    {"label": "Why is this product not selling?", "streams": ["Business & Management"]},
    {"label": "Why is this community struggling with access to something?", "streams": ["Healthcare & Social Sciences"]}
  ]'::jsonb,
  4
),
(
  'Your ideal work environment looks like...',
  '[
    {"label": "A lab, workshop, or writing code", "streams": ["Engineering & Technology"]},
    {"label": "A newsroom, studio, or creative space", "streams": ["Humanities & Media"]},
    {"label": "An office running a growing team or company", "streams": ["Business & Management"]},
    {"label": "A hospital, clinic, or community organization", "streams": ["Healthcare & Social Sciences"]}
  ]'::jsonb,
  5
);

-- ── challenge_questions ─────────────────────────────────────────────────
-- `options` is a plain array of strings; `correct_index` is 0-based.
-- Roughly class 9-12 difficulty, mixed math/science. `get_daily_challenge()`
-- picks 5 of these deterministically each day.
insert into public.challenge_questions (subject, question, options, correct_index) values
('math', 'What is the value of x in 2x + 5 = 17?', '["4", "5", "6", "7"]'::jsonb, 2),
('math', 'What is the square root of 144?', '["11", "12", "13", "14"]'::jsonb, 1),
('math', 'A train travels 300 km in 5 hours. What is its average speed?', '["50 km/h", "55 km/h", "60 km/h", "65 km/h"]'::jsonb, 0),
('math', 'What is the value of pi (π), rounded to two decimal places?', '["3.14", "3.16", "3.12", "3.18"]'::jsonb, 0),
('math', 'If a triangle has angles of 90° and 45°, what is the third angle?', '["30°", "35°", "45°", "50°"]'::jsonb, 2),
('math', 'What is 15% of 200?', '["20", "25", "30", "35"]'::jsonb, 2),
('science', 'What is the powerhouse of the cell?', '["Nucleus", "Ribosome", "Mitochondria", "Golgi body"]'::jsonb, 2),
('science', 'Which gas do plants absorb from the atmosphere for photosynthesis?', '["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"]'::jsonb, 2),
('science', 'What is the chemical symbol for Sodium?', '["So", "Sd", "Na", "S"]'::jsonb, 2),
('science', 'What force pulls objects toward the center of the Earth?', '["Magnetism", "Gravity", "Friction", "Tension"]'::jsonb, 1),
('science', 'What is the SI unit of electric current?', '["Volt", "Watt", "Ohm", "Ampere"]'::jsonb, 3),
('science', 'Which part of the human body is primarily responsible for pumping blood?', '["Lungs", "Liver", "Heart", "Kidneys"]'::jsonb, 2),
('vocabulary', 'What does "ubiquitous" mean?', '["Rare and hard to find", "Present everywhere", "Extremely expensive", "Difficult to understand"]'::jsonb, 1),
('vocabulary', 'Someone who is "eloquent" is best described as:', '["Fluent and persuasive in speech", "Very quiet and shy", "Easily confused", "Physically strong"]'::jsonb, 0),
('vocabulary', 'If a plan is "pragmatic", it is:', '["Overly complicated", "Sensible and realistic", "Based on emotion", "Impossible to achieve"]'::jsonb, 1),
('vocabulary', 'To "procrastinate" means to:', '["Finish early", "Delay or postpone", "Work quickly", "Ask for help"]'::jsonb, 1),
('vocabulary', 'A "meticulous" person pays close attention to:', '["Other peoples opinions", "Detail", "Money", "Time zones"]'::jsonb, 1),
('vocabulary', 'Being "resilient" means you:', '["Give up easily", "Recover quickly from setbacks", "Avoid all risks", "Ignore feedback"]'::jsonb, 1),
('vocabulary', 'A "concise" explanation is:', '["Long and detailed", "Clear and brief", "Confusing", "Written in another language"]'::jsonb, 1),
('vocabulary', 'If something is "arbitrary", it is:', '["Carefully planned", "Based on random choice", "Extremely rare", "Scientifically proven"]'::jsonb, 1);

-- ── vocabulary_words ────────────────────────────────────────────────────
-- The "Word of the Day" card pool. Class 9-12 English level, examples
-- written around student life so they land as relevant, not textbook-dry.
-- Single words only (no phrases/hyphenates) so scripts/enrich-vocabulary.mjs
-- can look each one up in the Free Dictionary API and slug the audio file
-- name off it. Examples avoid apostrophes/contractions to keep the SQL
-- string literals clean.
insert into public.vocabulary_words (word, part_of_speech, definition, example_sentence) values
('Ubiquitous', 'adjective', 'Present, appearing, or found everywhere.', 'Smartphones have become ubiquitous in modern classrooms.'),
('Eloquent', 'adjective', 'Fluent and persuasive in speaking or writing.', 'Her eloquent speech convinced the entire student council.'),
('Resilient', 'adjective', 'Able to recover quickly from difficulties.', 'Being resilient after a failed exam matters more than never failing.'),
('Ambiguous', 'adjective', 'Open to more than one interpretation.', 'The instructions were so ambiguous that half the class misunderstood them.'),
('Procrastinate', 'verb', 'To delay or postpone taking action.', 'I always procrastinate on assignments until the night before they are due.'),
('Meticulous', 'adjective', 'Showing great attention to detail.', 'She is meticulous about checking her math homework twice.'),
('Candid', 'adjective', 'Truthful and straightforward; frank.', 'The teacher gave candid feedback on my essay.'),
('Innovate', 'verb', 'To introduce new ideas or methods.', 'Young entrepreneurs are innovating faster than ever before.'),
('Skeptical', 'adjective', 'Not easily convinced; having doubts.', 'I am skeptical about claims that promise overnight success.'),
('Pragmatic', 'adjective', 'Dealing with things sensibly and realistically.', 'Choosing a stream based on your strengths is a pragmatic decision.'),
('Concise', 'adjective', 'Giving information clearly, in a few words.', 'A concise resume is more likely to actually get read.'),
('Tenacious', 'adjective', 'Persistent and determined.', 'Her tenacious attitude helped her master calculus despite struggling at first.'),
('Euphoric', 'adjective', 'Feeling intense happiness or excitement.', 'She felt euphoric after her first coding project actually worked.'),
('Arbitrary', 'adjective', 'Based on random choice, not reason.', 'The seating arrangement seemed completely arbitrary.'),
('Diligent', 'adjective', 'Showing care and effort in your work.', 'Diligent students review their notes every single day.'),
('Cogent', 'adjective', 'Clear, logical, and convincing.', 'She built a cogent argument for extending the project deadline.'),
('Succinct', 'adjective', 'Expressed clearly in very few words.', 'Keep your presentation succinct so people remember the main point.'),
('Verbose', 'adjective', 'Using far more words than necessary.', 'His verbose answers made a simple topic sound complicated.'),
('Astute', 'adjective', 'Quick to understand a situation and act on it.', 'An astute observation from the back of the class shifted the whole discussion.'),
('Prudent', 'adjective', 'Careful and sensible, especially about the future.', 'Saving part of your pocket money is a prudent habit to start early.'),
('Zealous', 'adjective', 'Full of energy and enthusiasm for a cause.', 'The zealous new club members organised three events in a month.'),
('Apathy', 'noun', 'A lack of interest, enthusiasm, or concern.', 'Voter apathy in the student council election worried the teachers.'),
('Empathy', 'noun', 'The ability to understand how another person feels.', 'Good group projects need empathy as much as they need talent.'),
('Nuance', 'noun', 'A very small difference in meaning, tone, or feeling.', 'The debate came down to a nuance that most students had missed.'),
('Paradox', 'noun', 'A statement that seems to contradict itself but may be true.', 'It is a paradox that the more you learn, the more you realise how little you know.'),
('Rhetoric', 'noun', 'The art of using language to persuade or impress.', 'The winning speech relied on real evidence, not just rhetoric.'),
('Scrutinize', 'verb', 'To examine something closely and critically.', 'Scrutinize the question paper for a minute before you start writing.'),
('Alleviate', 'verb', 'To make pain or a problem less severe.', 'A clear study timetable can alleviate a lot of exam stress.'),
('Advocate', 'verb', 'To publicly support a particular cause or idea.', 'She advocates for more practical lab time in the science curriculum.'),
('Emulate', 'verb', 'To try to match or do as well as someone you admire.', 'He tried to emulate the discipline of the class topper.'),
('Mitigate', 'verb', 'To make something bad less harmful or serious.', 'Reviewing your notes weekly mitigates the panic before finals.'),
('Facilitate', 'verb', 'To make an action or process easier.', 'A shared document facilitated the group project even though everyone lived far apart.'),
('Articulate', 'adjective', 'Able to express ideas clearly and fluently.', 'Being articulate in an interview matters more than using big words.'),
('Coherent', 'adjective', 'Logical, clear, and well organised.', 'Her essay was coherent from the first line to the conclusion.'),
('Redundant', 'adjective', 'Not needed because it repeats something already present.', 'The second paragraph was redundant and only weakened the essay.'),
('Superficial', 'adjective', 'Only on the surface; lacking depth.', 'A superficial reading of the chapter will not get you through the exam.'),
('Trivial', 'adjective', 'Of very little importance or value.', 'Do not lose marks over trivial spelling mistakes you could have caught.'),
('Profound', 'adjective', 'Very deep, intense, or insightful.', 'The book had a profound effect on how she saw her career choices.'),
('Inevitable', 'adjective', 'Certain to happen and impossible to avoid.', 'Some failure is inevitable when you are learning a hard new skill.'),
('Feasible', 'adjective', 'Possible to do without too much difficulty.', 'Finishing the model in one weekend was just about feasible.'),
('Viable', 'adjective', 'Able to work successfully.', 'The team needed a viable plan, not just an exciting one.'),
('Obsolete', 'adjective', 'Out of date and no longer used.', 'The lab manual referred to software that is now obsolete.'),
('Intrinsic', 'adjective', 'Belonging naturally to something; essential.', 'Curiosity is intrinsic to good research.'),
('Autonomy', 'noun', 'The freedom to make your own decisions.', 'Older students were given more autonomy over their project topics.'),
('Consensus', 'noun', 'General agreement within a group.', 'The class reached a consensus on the trip destination after a long discussion.'),
('Criterion', 'noun', 'A standard used to judge or decide something.', 'Originality was the main criterion for the science fair prize.'),
('Hypothesis', 'noun', 'A proposed explanation that can be tested.', 'Write down your hypothesis before you run the experiment, not after.'),
('Incentive', 'noun', 'Something that encourages a person to act.', 'Bonus marks were the incentive to submit the assignment early.'),
('Rationale', 'noun', 'The set of reasons behind a decision.', 'Explain the rationale for your method in the project report.'),
('Bias', 'noun', 'An unfair leaning toward or against something.', 'Good sources try to report the facts without bias.'),
('Integrity', 'noun', 'The quality of being honest and having firm principles.', 'Academic integrity means the work you submit is genuinely your own.'),
('Adversity', 'noun', 'A difficult or unpleasant situation.', 'She spoke about facing adversity after switching schools mid year.'),
('Ambivalent', 'adjective', 'Having mixed or conflicting feelings about something.', 'He felt ambivalent about joining the debate team and the coding club at once.'),
('Complacent', 'adjective', 'So satisfied with yourself that you stop trying to improve.', 'One good test result made him complacent, and the next one slipped.'),
('Conscientious', 'adjective', 'Careful to do your work thoroughly and well.', 'A conscientious student checks the marking scheme before submitting.'),
('Versatile', 'adjective', 'Able to adapt to many different tasks or roles.', 'A versatile teammate can present, design, and write when needed.'),
('Proficient', 'adjective', 'Skilled and competent at something.', 'Two months of daily practice made her proficient in basic Python.'),
('Erratic', 'adjective', 'Irregular and unpredictable.', 'His erratic sleep schedule showed up in his morning classes.'),
('Volatile', 'adjective', 'Likely to change suddenly and unpredictably.', 'The group mood was volatile the week before the board exams.'),
('Sporadic', 'adjective', 'Happening at irregular intervals; scattered.', 'Sporadic studying rarely beats a steady half hour every day.'),
('Transient', 'adjective', 'Lasting only for a short time.', 'The disappointment of a low mark is usually transient.'),
('Elaborate', 'verb', 'To add more detail to something already said.', 'The examiner asked her to elaborate on her second point.'),
('Condense', 'verb', 'To make something shorter or more concentrated.', 'Try to condense the chapter into one page of notes.'),
('Delegate', 'verb', 'To give part of your work or authority to someone else.', 'A good group leader will delegate tasks instead of doing everything alone.'),
('Persevere', 'verb', 'To keep going despite difficulty or delay.', 'She persevered with the proof until it finally made sense.'),
('Contemplate', 'verb', 'To think about something carefully and for a long time.', 'He spent the summer contemplating whether to take commerce or science.'),
('Speculate', 'verb', 'To form an opinion without having full evidence.', 'Do not speculate about the results before the experiment is done.'),
('Undermine', 'verb', 'To weaken something gradually or secretly.', 'Skipping the basics will undermine everything you build later.'),
('Reinforce', 'verb', 'To make something stronger or more firmly established.', 'Solving extra problems reinforces what you learned in class.'),
('Diminish', 'verb', 'To make or become smaller or less.', 'Regular revision diminishes the fear of a big syllabus.'),
('Distort', 'verb', 'To twist something out of its true shape or meaning.', 'A rushed summary can distort what the author actually argued.'),
('Fluctuate', 'verb', 'To rise and fall in an irregular way.', 'Her marks fluctuated until she fixed her revision routine.'),
('Prevalent', 'adjective', 'Widespread; common in a place or time.', 'The belief that you must choose engineering is still prevalent among many parents.'),
('Notorious', 'adjective', 'Well known for something bad.', 'That chapter is notorious for tricky application questions.'),
('Prominent', 'adjective', 'Important, well known, or easily noticed.', 'A prominent alumnus came back to talk about life after school.'),
('Credible', 'adjective', 'Believable and able to be trusted.', 'Cite credible sources, not the first blog you find.'),
('Plausible', 'adjective', 'Seeming reasonable or likely to be true.', 'Her explanation for the missing data was plausible enough to accept.'),
('Legitimate', 'adjective', 'Allowed by the rules; genuine and justifiable.', 'A note from a doctor is a legitimate reason to reschedule the test.'),
('Impartial', 'adjective', 'Not favouring one side; fair.', 'The judges stayed impartial even when their own school competed.'),
('Objective', 'adjective', 'Based on facts rather than personal feelings.', 'Try to be objective when you grade your own practice essay.'),
('Subjective', 'adjective', 'Based on personal opinion or feeling.', 'Whether a film is good is partly subjective, but the editing quality is not.'),
('Comprehensive', 'adjective', 'Complete; covering all or nearly all parts.', 'She made a comprehensive revision sheet for the entire unit.'),
('Rigorous', 'adjective', 'Extremely thorough, careful, and demanding.', 'The coach set a rigorous training plan for the science olympiad.'),
('Analytical', 'adjective', 'Relating to careful, step by step reasoning.', 'Physics rewards an analytical approach more than memorising.'),
('Abstract', 'adjective', 'Existing as an idea rather than a physical object.', 'Algebra felt abstract until she connected it to real problems.'),
('Tangible', 'adjective', 'Real and definite; able to be seen or touched.', 'Finishing a working prototype gave the team something tangible to show.'),
('Elusive', 'adjective', 'Hard to find, catch, or achieve.', 'A full night of sleep was elusive during exam week.'),
('Deliberate', 'adjective', 'Done on purpose and with full awareness.', 'Her calm tone in the debate was a deliberate choice.'),
('Spontaneous', 'adjective', 'Happening naturally, without being planned.', 'The best answers in the viva were spontaneous, not memorised.'),
('Reluctant', 'adjective', 'Unwilling and slow to act.', 'He was reluctant to ask for help until the topic became impossible.'),
('Assertive', 'adjective', 'Confident and direct in stating your needs or views.', 'Being assertive in a group means sharing your idea without talking over others.'),
('Arrogant', 'adjective', 'Having an exaggerated sense of your own importance.', 'Confidence helps in an interview; sounding arrogant does not.'),
('Gracious', 'adjective', 'Kind, polite, and pleasant, especially toward juniors.', 'She was gracious to the junior team even after winning.'),
('Hostile', 'adjective', 'Unfriendly and opposed.', 'A hostile tone in a group chat kills honest discussion fast.'),
('Indignant', 'adjective', 'Angry because something seems unfair.', 'The class was indignant when the trip was cancelled without a reason.'),
('Apprehensive', 'adjective', 'Worried that something bad might happen.', 'Most students feel apprehensive before their first oral exam.'),
('Impulsive', 'adjective', 'Acting suddenly without thinking it through.', 'Choosing a stream on an impulsive whim is a decision worth slowing down.'),
('Frugal', 'adjective', 'Careful and sparing with money or resources.', 'A frugal approach to the project budget left room for mistakes.'),
('Scarce', 'adjective', 'Available in smaller quantity than needed.', 'Quiet study spots become scarce during exam season.'),
('Abundant', 'adjective', 'Present in large quantity; more than enough.', 'Free learning resources are abundant online if you know where to look.'),
('Adept', 'adjective', 'Highly skilled at something.', 'She is adept at explaining hard ideas in plain words.'),
('Aesthetic', 'adjective', 'Concerned with beauty and how something looks.', 'The team lost marks because the app worked but had no aesthetic sense.'),
('Affable', 'adjective', 'Friendly and easy to talk to.', 'The new teacher was so affable that students actually asked questions.'),
('Altruistic', 'adjective', 'Selflessly concerned for the welfare of others.', 'Tutoring juniors for free was a genuinely altruistic thing to do.'),
('Amiable', 'adjective', 'Having a pleasant and friendly manner.', 'An amiable group leader keeps everyone contributing.'),
('Anecdote', 'noun', 'A short personal story used to make a point.', 'Open your speech with an anecdote instead of a definition.'),
('Anomaly', 'noun', 'Something that differs from what is normal or expected.', 'One anomaly in the data set made her repeat the whole experiment.'),
('Ascend', 'verb', 'To rise or move upward.', 'Her marks ascended steadily once she fixed her sleep schedule.'),
('Assimilate', 'verb', 'To take in and fully understand information.', 'Do not try to assimilate three chapters in one night.'),
('Audacious', 'adjective', 'Boldly daring, with little regard for risk.', 'Entering the national contest in class 9 was an audacious move that paid off.'),
('Austere', 'adjective', 'Severe or plain in appearance or manner.', 'The exam hall had an austere, silent feel that made everyone nervous.'),
('Benevolent', 'adjective', 'Kind and wanting to help others.', 'A benevolent senior spent lunch helping the class revise.'),
('Benign', 'adjective', 'Gentle and harmless.', 'The feedback sounded harsh but the intent was benign.'),
('Bewilder', 'verb', 'To confuse someone completely.', 'The last question bewildered even the toppers.'),
('Blatant', 'adjective', 'Done openly and without shame.', 'Copying in blatant view of the invigilator got him disqualified.'),
('Brevity', 'noun', 'Shortness in speaking or writing.', 'Brevity in an answer is fine if every sentence earns a mark.'),
('Buoyant', 'adjective', 'Cheerful and optimistic.', 'The class stayed buoyant even after a tough physics paper.'),
('Cacophony', 'noun', 'A harsh mixture of loud sounds.', 'The cacophony of the corridor made it impossible to focus.'),
('Camaraderie', 'noun', 'A feeling of friendship and trust within a group.', 'Late-night project sessions built real camaraderie in the team.'),
('Candour', 'noun', 'Honest and direct speech.', 'She answered the interviewer with surprising candour.'),
('Capitulate', 'verb', 'To give in or surrender.', 'Do not capitulate on a hard problem after only five minutes.'),
('Censure', 'verb', 'To express strong formal disapproval of.', 'The council was censured for spending the budget without a vote.'),
('Circumspect', 'adjective', 'Careful to weigh all consequences before acting.', 'Be circumspect about which sources you trust online.'),
('Coerce', 'verb', 'To force someone to act through pressure or threats.', 'A good teacher inspires rather than tries to coerce.'),
('Cohesion', 'noun', 'The quality of forming a united whole.', 'The essay had good points but lacked cohesion between paragraphs.'),
('Collate', 'verb', 'To collect and combine information in order.', 'She collated the group notes into one shared document.'),
('Colloquial', 'adjective', 'Used in ordinary conversation, not formal writing.', 'Keep colloquial phrases out of a formal essay.'),
('Commend', 'verb', 'To praise formally.', 'The judges commended the project for its originality.'),
('Compelling', 'adjective', 'Powerfully convincing or interesting.', 'A compelling opening line makes the examiner want to keep reading.'),
('Complement', 'verb', 'To add to something in a way that improves it.', 'Diagrams complement a written explanation in a biology answer.'),
('Concur', 'verb', 'To agree.', 'Most of the panel concurred with her conclusion.'),
('Condescending', 'adjective', 'Acting as if you are superior to others.', 'Explaining something without sounding condescending is a real skill.'),
('Confound', 'verb', 'To confuse or surprise someone.', 'The twist in the case study confounded the whole class.'),
('Congenial', 'adjective', 'Pleasant and agreeable.', 'A congenial study group makes long sessions bearable.'),
('Conjecture', 'noun', 'An opinion formed without full evidence.', 'Until you test it, your idea is just conjecture.'),
('Connotation', 'noun', 'An idea a word suggests beyond its literal meaning.', 'The word cheap has a negative connotation that affordable does not.'),
('Contentious', 'adjective', 'Likely to cause disagreement.', 'The debate topic was chosen to be deliberately contentious.'),
('Contrite', 'adjective', 'Feeling genuine regret for a wrong.', 'A contrite apology repairs more than an excuse does.'),
('Conundrum', 'noun', 'A difficult problem or puzzle.', 'Balancing sports practice and board prep was a real conundrum.'),
('Copious', 'adjective', 'Large in quantity; plentiful.', 'She took copious notes and thanked herself later.'),
('Corroborate', 'verb', 'To confirm or support with evidence.', 'A second source corroborated the date in her history essay.'),
('Culpable', 'adjective', 'Deserving blame.', 'The whole group was culpable for missing the deadline, not just the leader.'),
('Cursory', 'adjective', 'Quick and not thorough.', 'A cursory glance at the syllabus is not the same as revising it.'),
('Debunk', 'verb', 'To show that a belief is false.', 'The chapter debunks the myth that you cannot improve at maths.'),
('Decorum', 'noun', 'Behaviour that is polite and appropriate.', 'Maintain decorum in the exam hall even when a question annoys you.'),
('Deft', 'adjective', 'Quick and skilful.', 'A deft edit cut her essay in half without losing anything.'),
('Delineate', 'verb', 'To describe or mark out precisely.', 'The rubric delineates exactly what earns full marks.'),
('Demeanour', 'noun', 'The way a person behaves or carries themselves.', 'Her calm demeanour in the viva impressed the panel.'),
('Deride', 'verb', 'To mock or ridicule.', 'Nobody learns in a class where mistakes get derided.'),
('Derivative', 'adjective', 'Copied from something else; not original.', 'The design was clean but felt derivative of an app everyone knew.'),
('Despondent', 'adjective', 'In low spirits from a loss of hope.', 'She felt despondent after the mock but recovered with a new plan.'),
('Detrimental', 'adjective', 'Causing harm.', 'All-nighters before an exam are usually detrimental to your score.'),
('Dexterity', 'noun', 'Skill in using the hands or the mind.', 'Lab work rewards manual dexterity as much as theory.'),
('Diffident', 'adjective', 'Shy and lacking self-confidence.', 'She was too diffident to raise her hand even when she knew the answer.'),
('Digress', 'verb', 'To move away from the main subject.', 'The lecture was good but the speaker digressed for ten minutes.'),
('Diligence', 'noun', 'Careful and persistent effort.', 'Diligence over weeks beats panic over one weekend.'),
('Discord', 'noun', 'Disagreement or lack of harmony.', 'A clear plan removed most of the discord in the group.'),
('Discrepancy', 'noun', 'A difference between things that should match.', 'A discrepancy between her two readings meant a measurement error.'),
('Disdain', 'noun', 'A feeling that something is unworthy of respect.', 'Treating a subject with disdain usually shows up in the marks.'),
('Disparage', 'verb', 'To speak of someone or something in a belittling way.', 'Do not disparage a career path just because it is unfamiliar.'),
('Disparate', 'adjective', 'Very different from one another.', 'She combined disparate ideas from art and biology into one project.'),
('Dispassionate', 'adjective', 'Calm and fair; not driven by emotion.', 'A dispassionate review of your own work catches more mistakes.'),
('Disseminate', 'verb', 'To spread information widely.', 'The club used posters to disseminate the event details.'),
('Dogmatic', 'adjective', 'Stating your views as if they cannot be wrong.', 'A dogmatic tone weakens even a good argument.'),
('Dubious', 'adjective', 'Doubtful or questionable.', 'A website with no named author is a dubious source.'),
('Ebullient', 'adjective', 'Full of energy and cheerful excitement.', 'She was ebullient after the acceptance email arrived.'),
('Eclectic', 'adjective', 'Made up of parts from many different sources.', 'His eclectic reading list ranged from physics to poetry.'),
('Efficacy', 'noun', 'The ability to produce a desired result.', 'They tested the efficacy of spaced revision against cramming.'),
('Egregious', 'adjective', 'Outstandingly bad; shocking.', 'Forgetting to write your name is an egregious but common error.'),
('Emphatic', 'adjective', 'Expressed with force and clarity.', 'He was emphatic that the deadline would not move.'),
('Empirical', 'adjective', 'Based on observation or experiment, not theory alone.', 'Back your claim with empirical data, not just reasoning.'),
('Enigma', 'noun', 'Something mysterious or hard to understand.', 'The marking scheme stayed an enigma until results day.'),
('Ephemeral', 'adjective', 'Lasting for a very short time.', 'Exam stress feels huge but is largely ephemeral.'),
('Epitome', 'noun', 'A perfect example of a quality or type.', 'Her notebook was the epitome of organised revision.'),
('Equanimity', 'noun', 'Calmness and composure under pressure.', 'He answered the surprise question with total equanimity.'),
('Equitable', 'adjective', 'Fair and impartial.', 'An equitable group splits the work by strength, not by seniority.'),
('Erudite', 'adjective', 'Showing deep and wide knowledge.', 'The guest speaker was erudite without being hard to follow.'),
('Esoteric', 'adjective', 'Understood by only a small group with special knowledge.', 'He got lost in esoteric detail the examiner never asked for.'),
('Euphemism', 'noun', 'A mild word used in place of a harsh one.', 'Needs improvement is a euphemism every student learns to read.'),
('Exacerbate', 'verb', 'To make a problem worse.', 'Skipping sleep exacerbates exam anxiety.'),
('Exemplary', 'adjective', 'Serving as an excellent model.', 'Her lab report was used as an exemplary answer the next year.'),
('Exhaustive', 'adjective', 'Complete and thorough.', 'She made an exhaustive list of every formula in the unit.'),
('Exonerate', 'verb', 'To clear of blame.', 'The timestamp exonerated him from the charge of a late submission.'),
('Expedient', 'adjective', 'Convenient and practical, but sometimes not fair.', 'Copying was the expedient choice and the wrong one.'),
('Expedite', 'verb', 'To make a process happen faster.', 'A clear subject line can expedite a reply from a teacher.'),
('Facetious', 'adjective', 'Joking at an inappropriate moment.', 'A facetious answer in a viva rarely lands well.'),
('Fallacy', 'noun', 'A mistaken belief based on faulty reasoning.', 'It is a fallacy that talent matters more than practice.'),
('Fastidious', 'adjective', 'Very attentive to detail and neatness.', 'He is fastidious about labelling every diagram.'),
('Fervent', 'adjective', 'Showing intense, passionate feeling.', 'She made a fervent case for keeping the library open later.'),
('Flippant', 'adjective', 'Not showing a serious or respectful attitude.', 'A flippant reply to feedback wastes the feedback.'),
('Formidable', 'adjective', 'Inspiring respect through size or difficulty.', 'The syllabus looked formidable until she broke it into weeks.'),
('Fortuitous', 'adjective', 'Happening by chance, usually luckily.', 'Meeting a mentor at the science fair was entirely fortuitous.'),
('Frivolous', 'adjective', 'Not serious or worthwhile.', 'Cut the frivolous sentences and the essay gets stronger.'),
('Furtive', 'adjective', 'Secretive, as if hiding something.', 'A furtive glance at a phone during the test is enough to be caught.'),
('Galvanise', 'verb', 'To shock or spur someone into action.', 'A poor mock result galvanised the whole class into a routine.'),
('Garrulous', 'adjective', 'Talking too much about unimportant things.', 'A garrulous partner can derail a timed group task.'),
('Glib', 'adjective', 'Fluent but insincere or shallow.', 'A glib answer sounds smooth but earns nothing.'),
('Grandiose', 'adjective', 'Impressive in a way that seems exaggerated.', 'The plan was grandiose but the team was three people.'),
('Gratuitous', 'adjective', 'Done without good reason; uncalled for.', 'The report had gratuitous detail that buried the finding.'),
('Gregarious', 'adjective', 'Sociable and fond of company.', 'A gregarious student often finds group projects easier.'),
('Hackneyed', 'adjective', 'Overused and no longer interesting.', 'Follow your dreams is a hackneyed way to end a speech.'),
('Hapless', 'adjective', 'Unlucky.', 'The hapless team drew the hardest topic in the debate.'),
('Harbinger', 'noun', 'A sign of something to come.', 'Falling attendance was a harbinger of a difficult term.'),
('Haughty', 'adjective', 'Arrogantly superior.', 'A haughty attitude in a group makes people stop sharing ideas.'),
('Hiatus', 'noun', 'A pause or gap in an activity.', 'After a short hiatus for exams, the club met again.'),
('Hone', 'verb', 'To sharpen or refine a skill.', 'She used past papers to hone her timing, not her knowledge.'),
('Idiosyncrasy', 'noun', 'A distinctive personal habit or quirk.', 'Writing the date in the margin was her idiosyncrasy.'),
('Immaculate', 'adjective', 'Perfectly clean or free of error.', 'His immaculate handwriting made the answer easy to mark.'),
('Immutable', 'adjective', 'Unchanging over time.', 'The rules of the exam are immutable once it starts.'),
('Impeccable', 'adjective', 'Faultless.', 'Her citation format was impeccable.'),
('Impetuous', 'adjective', 'Acting quickly without thought.', 'An impetuous answer often misses half the question.'),
('Implacable', 'adjective', 'Impossible to calm or satisfy.', 'The deadline is implacable, so plan backward from it.'),
('Inadvertent', 'adjective', 'Not intentional.', 'An inadvertent skipped page cost him ten marks.'),
('Incessant', 'adjective', 'Continuing without pause.', 'The incessant notifications made an hour of study feel like ten minutes.'),
('Incisive', 'adjective', 'Showing sharp, clear thinking.', 'One incisive question from the back changed the whole discussion.'),
('Incongruous', 'adjective', 'Out of place; not fitting.', 'A joke felt incongruous in an otherwise serious report.'),
('Indefatigable', 'adjective', 'Never tiring.', 'The indefatigable club secretary answered messages at midnight.'),
('Indolent', 'adjective', 'Wanting to avoid effort; lazy.', 'One indolent week in a hard subject is hard to recover from.'),
('Ineffable', 'adjective', 'Too great to be put into words.', 'The relief after the last paper was almost ineffable.'),
('Inept', 'adjective', 'Having no skill; clumsy.', 'Practice turned an inept first draft into a solid essay.'),
('Inexorable', 'adjective', 'Impossible to stop or prevent.', 'Results day approached with inexorable speed.'),
('Ingenious', 'adjective', 'Clever, original, and inventive.', 'She found an ingenious shortcut for the proof.'),
('Ingenuous', 'adjective', 'Innocent, sincere, and unsuspecting.', 'His ingenuous question turned out to be the smartest one asked.'),
('Innocuous', 'adjective', 'Harmless.', 'An innocuous typo in the title still looks careless.'),
('Insatiable', 'adjective', 'Impossible to satisfy.', 'She had an insatiable appetite for one more practice problem.'),
('Insidious', 'adjective', 'Harmful in a gradual, hidden way.', 'Comparing yourself to others is an insidious study habit.'),
('Insipid', 'adjective', 'Lacking flavour or interest.', 'An insipid conclusion undoes a strong essay.'),
('Instigate', 'verb', 'To bring about or start something.', 'One student instigated the petition for a later library.'),
('Insular', 'adjective', 'Not open to other people or ideas.', 'An insular study group misses out on better methods.'),
('Interminable', 'adjective', 'Seeming to have no end.', 'The wait between the exam and the results felt interminable.'),
('Intrepid', 'adjective', 'Fearless and adventurous.', 'An intrepid junior signed up for the senior olympiad.'),
('Inundate', 'verb', 'To overwhelm with a large amount of something.', 'The week before finals can inundate you if you have no plan.'),
('Irascible', 'adjective', 'Easily angered.', 'An irascible mood before an exam usually means you need sleep.'),
('Judicious', 'adjective', 'Showing good judgement.', 'A judicious use of your last ten minutes is to check, not to keep writing.'),
('Juxtapose', 'verb', 'To place things side by side for contrast.', 'The essay juxtaposes two leaders to show a difference in style.'),
('Laconic', 'adjective', 'Using very few words.', 'His laconic answers were correct but cost him easy marks.'),
('Lament', 'verb', 'To express deep sadness or regret.', 'She lamented not starting revision a month earlier.'),
('Languid', 'adjective', 'Slow and lacking energy.', 'The class felt languid on the afternoon after sports day.'),
('Latent', 'adjective', 'Present but not yet visible or active.', 'A latent talent for design showed up in her first project.'),
('Laudable', 'adjective', 'Deserving praise.', 'Volunteering every weekend is a laudable commitment.'),
('Lucid', 'adjective', 'Clear and easy to understand.', 'A lucid explanation is worth more than a long one.'),
('Lucrative', 'adjective', 'Producing a lot of money.', 'A lucrative field is not worth it if the work bores you daily.'),
('Ludicrous', 'adjective', 'So foolish it is laughable.', 'The idea of learning a language in a weekend is ludicrous.'),
('Magnanimous', 'adjective', 'Generous and forgiving, especially toward a rival.', 'The losing team was magnanimous in defeat.'),
('Malleable', 'adjective', 'Easily shaped or influenced.', 'First-year habits are malleable, so build good ones early.'),
('Meander', 'verb', 'To wander without a direct course.', 'An answer that meanders loses the examiner halfway.'),
('Mediocre', 'adjective', 'Of only average quality.', 'A mediocre draft becomes good with one honest revision.'),
('Mercurial', 'adjective', 'Changing mood quickly and unpredictably.', 'His mercurial focus made group planning difficult.'),
('Mundane', 'adjective', 'Ordinary and dull.', 'Even mundane daily revision adds up over a term.'),
('Myriad', 'noun', 'A very large number of things.', 'There are a myriad of free courses past the first search result.'),
('Nebulous', 'adjective', 'Unclear or vague.', 'A nebulous thesis makes the whole essay wobble.'),
('Nominal', 'adjective', 'Very small; in name only.', 'The club charged a nominal fee just to cover printing.'),
('Nonchalant', 'adjective', 'Calm and seemingly unconcerned.', 'She stayed nonchalant even as the timer hit five minutes.'),
('Nostalgia', 'noun', 'A sentimental longing for the past.', 'Final year brings a strange nostalgia for classes you used to dread.'),
('Novice', 'noun', 'A person new to an activity.', 'Every expert coder was once a novice who kept going.'),
('Nurture', 'verb', 'To care for and encourage growth.', 'A good mentor nurtures curiosity instead of grading it.'),
('Obfuscate', 'verb', 'To make something unclear on purpose.', 'Big words used to obfuscate a weak point rarely fool an examiner.'),
('Oblivious', 'adjective', 'Not aware of what is happening around you.', 'He was oblivious to the time until the bell rang.'),
('Obsequious', 'adjective', 'Excessively eager to please.', 'Being obsequious to a teacher is not the same as being respectful.'),
('Ominous', 'adjective', 'Suggesting that something bad is coming.', 'The silence before the results was ominous.'),
('Onerous', 'adjective', 'Involving a lot of effort and difficulty.', 'The reading list looked onerous until she split it by week.'),
('Opaque', 'adjective', 'Hard to see through or understand.', 'The instructions were so opaque that the teacher rewrote them.'),
('Ornate', 'adjective', 'Highly decorated and elaborate.', 'An ornate cover cannot save a thin project.'),
('Ostracise', 'verb', 'To exclude someone from a group.', 'One mistake should not get a teammate ostracised.'),
('Palatable', 'adjective', 'Acceptable or pleasant.', 'Honest feedback is more palatable when it comes with a next step.'),
('Palpable', 'adjective', 'So strong it can almost be felt.', 'The tension in the hall before the paper was palpable.'),
('Paltry', 'adjective', 'Very small or meagre.', 'A paltry effort in the easy section is where marks quietly leak.'),
('Paradigm', 'noun', 'A typical model or pattern of something.', 'Online learning shifted the paradigm for how students study.'),
('Paramount', 'adjective', 'More important than anything else.', 'Understanding the question is paramount before you write a word.'),
('Pedantic', 'adjective', 'Overly concerned with tiny details or rules.', 'A pedantic focus on font wasted the group an hour.'),
('Penchant', 'noun', 'A strong liking for something.', 'She has a penchant for turning notes into colourful diagrams.'),
('Perfunctory', 'adjective', 'Done with minimum effort or care.', 'A perfunctory apology to a teammate fixes nothing.'),
('Pernicious', 'adjective', 'Causing harm in a subtle, gradual way.', 'The pernicious habit of studying with notifications on cost him weeks.'),
('Perpetuate', 'verb', 'To make something continue.', 'Repeating a rumour only perpetuates it.'),
('Peruse', 'verb', 'To read or examine carefully.', 'Peruse the whole paper before choosing which question to start.'),
('Petulant', 'adjective', 'Childishly sulky or bad-tempered.', 'A petulant reaction to a low mark hides the lesson in it.'),
('Philanthropic', 'adjective', 'Seeking to help others, especially through giving.', 'A philanthropic alumni fund covers exam fees for some students.'),
('Placate', 'verb', 'To calm someone down.', 'A clear timeline placated the worried parents.'),
('Placid', 'adjective', 'Calm and not easily upset.', 'Her placid manner steadied the group before the presentation.'),
('Plethora', 'noun', 'An excess or very large amount.', 'A plethora of open tabs is not the same as research.'),
('Poignant', 'adjective', 'Deeply moving or touching.', 'The last assembly had a poignant farewell speech.'),
('Ponderous', 'adjective', 'Slow and heavy; dull.', 'A ponderous introduction makes the reader work too hard.'),
('Precarious', 'adjective', 'Not securely held; risky.', 'Leaving all revision to the final week is a precarious plan.'),
('Precocious', 'adjective', 'Showing advanced ability at an early age.', 'The precocious ninth grader was solving twelfth grade problems.'),
('Predicament', 'noun', 'A difficult or unpleasant situation.', 'Missing the form deadline put her in a real predicament.'),
('Preposterous', 'adjective', 'Completely unreasonable; absurd.', 'The claim of a guaranteed rank was preposterous.'),
('Prescient', 'adjective', 'Knowing or predicting things before they happen.', 'Her prescient advice about the mock saved the class in finals.'),
('Presumptuous', 'adjective', 'Too bold or confident; overstepping.', 'It felt presumptuous to correct the teacher, but she was right.'),
('Pretext', 'noun', 'A false reason given to hide the real one.', 'He left on the pretext of a headache to avoid the presentation.'),
('Proclivity', 'noun', 'A natural tendency toward something.', 'She has a proclivity for asking why until it makes sense.'),
('Procure', 'verb', 'To obtain something with effort.', 'The club procured a projector by asking three departments.'),
('Prodigious', 'adjective', 'Remarkably large in size or degree.', 'He put in a prodigious amount of practice before the olympiad.'),
('Prolific', 'adjective', 'Producing a great deal of work.', 'A prolific note-taker still needs to review, not just collect.'),
('Propensity', 'noun', 'A tendency to behave in a certain way.', 'A propensity to skip the easy questions quietly costs marks.'),
('Prosaic', 'adjective', 'Plain and unimaginative.', 'A prosaic title is fine if the content is sharp.'),
('Provincial', 'adjective', 'Narrow in outlook; unsophisticated.', 'Reading widely cures a provincial view of careers.'),
('Pugnacious', 'adjective', 'Eager to argue or fight.', 'A pugnacious debater still needs evidence, not just volume.'),
('Quandary', 'noun', 'A state of uncertainty over what to do.', 'She was in a quandary about which two subjects to drop.'),
('Quell', 'verb', 'To put an end to; to calm.', 'A quick briefing quelled the panic about the changed timetable.'),
('Querulous', 'adjective', 'Complaining in a whiny way.', 'A querulous tone in a group chat drains everyone.'),
('Quintessential', 'adjective', 'The most perfect example of a type.', 'Her planner was the quintessential organised-student notebook.'),
('Rancour', 'noun', 'Bitter, long-lasting resentment.', 'The two teams competed hard but without rancour.'),
('Rebuke', 'verb', 'To criticise sharply.', 'He was rebuked for talking during the reading time.'),
('Recalcitrant', 'adjective', 'Stubbornly resistant to control or authority.', 'A recalcitrant printer nearly ruined the submission.'),
('Reciprocal', 'adjective', 'Given and received in return; mutual.', 'Good study partners have a reciprocal deal on explaining topics.'),
('Reclusive', 'adjective', 'Avoiding the company of other people.', 'She went briefly reclusive during finals and resurfaced fine.'),
('Rectitude', 'noun', 'Morally correct behaviour.', 'The head girl was chosen as much for rectitude as for grades.'),
('Refute', 'verb', 'To prove that a statement is wrong.', 'Use one clear counterexample to refute a shaky claim.'),
('Relegate', 'verb', 'To move to a lower position.', 'Weak time management relegated a smart student to average marks.'),
('Remiss', 'adjective', 'Careless about a duty.', 'It would be remiss not to thank the teachers who stayed late.'),
('Reprehensible', 'adjective', 'Deserving strong criticism.', 'Sabotaging another team project is reprehensible, not clever.'),
('Reprimand', 'verb', 'To rebuke formally.', 'The captain was reprimanded for arguing with the referee.'),
('Repudiate', 'verb', 'To reject or refuse to accept.', 'He repudiated the rumour in front of the whole class.'),
('Rescind', 'verb', 'To cancel or take back officially.', 'The school rescinded the rule after the student council objected.'),
('Resolute', 'adjective', 'Firmly determined.', 'She stayed resolute about her target school despite the pressure.'),
('Reticent', 'adjective', 'Not revealing your thoughts readily.', 'He was reticent in class but wrote brilliant essays.'),
('Reverence', 'noun', 'Deep respect.', 'They spoke about the retiring principal with real reverence.'),
('Rife', 'adjective', 'Widespread, usually of something bad.', 'Misinformation about exam patterns is rife online.'),
('Sagacious', 'adjective', 'Wise and showing good judgement.', 'A sagacious senior told her to master the basics first.'),
('Salient', 'adjective', 'Most noticeable or important.', 'Underline the salient points before you start the essay.'),
('Sanctimonious', 'adjective', 'Making a show of being morally superior.', 'A sanctimonious lecture about effort helps no one.'),
('Sanguine', 'adjective', 'Cheerfully optimistic in a hard situation.', 'She stayed sanguine about the retest and treated it as a second chance.'),
('Scathing', 'adjective', 'Severely critical.', 'The feedback was scathing but every point was fair.'),
('Scrupulous', 'adjective', 'Very careful to do the right thing.', 'She was scrupulous about crediting every source.'),
('Sedentary', 'adjective', 'Involving much sitting; inactive.', 'Long sedentary study sessions need a short walk every hour.'),
('Serendipity', 'noun', 'A pleasant discovery made by chance.', 'Finding her favourite subject was pure serendipity.'),
('Servile', 'adjective', 'Excessively willing to obey others.', 'Respecting a teacher is not the same as being servile.'),
('Solace', 'noun', 'Comfort in a time of distress.', 'She found solace in the fact that everyone found the paper hard.'),
('Solicitous', 'adjective', 'Showing careful concern for someone.', 'The class was solicitous toward the student who had been ill.'),
('Sombre', 'adjective', 'Dark and serious in mood.', 'The mood was sombre after the tough chemistry paper.'),
('Spurious', 'adjective', 'False, though seeming genuine.', 'A spurious statistic can sink an otherwise honest essay.'),
('Squander', 'verb', 'To waste something valuable.', 'Do not squander the first ten minutes reading the paper twice.'),
('Stagnant', 'adjective', 'Not moving or developing.', 'Her marks were stagnant until she changed how she revised.'),
('Steadfast', 'adjective', 'Firm and unwavering.', 'He was steadfast about finishing the project properly.'),
('Stoic', 'adjective', 'Enduring hardship without showing feeling.', 'She was stoic about the result and asked for the paper back to learn from it.'),
('Strident', 'adjective', 'Loud and harsh.', 'A strident tone in a debate can lose the neutral listeners.'),
('Stringent', 'adjective', 'Strict and precise.', 'The lab has stringent rules about wearing safety goggles.'),
('Subservient', 'adjective', 'Willing to obey others without question.', 'Good group members are collaborative, not subservient.'),
('Substantiate', 'verb', 'To support a claim with evidence.', 'Every point in the report should substantiate the conclusion.'),
('Superfluous', 'adjective', 'More than is needed; unnecessary.', 'Cut superfluous words and the argument gets sharper.'),
('Surmise', 'verb', 'To guess from limited evidence.', 'From the hint, she surmised the exam would focus on optics.'),
('Surpass', 'verb', 'To do better than.', 'Her mock score surpassed her own target by ten marks.'),
('Susceptible', 'adjective', 'Easily influenced or harmed.', 'Tired students are susceptible to careless mistakes.'),
('Sycophant', 'noun', 'A person who flatters others to gain advantage.', 'The class could tell effort apart from a sycophant.'),
('Taciturn', 'adjective', 'Saying very little.', 'He was taciturn in meetings but delivered his part first.'),
('Tantamount', 'adjective', 'Equal in effect to something.', 'Ignoring the rubric is tantamount to throwing away marks.'),
('Tedious', 'adjective', 'Boringly long and slow.', 'Formatting citations is tedious but it protects your marks.'),
('Temerity', 'noun', 'Excessive boldness; nerve.', 'She had the temerity to challenge a marking decision, and won.'),
('Tentative', 'adjective', 'Not certain or fixed; provisional.', 'Pencil in a tentative timetable and adjust it weekly.'),
('Terse', 'adjective', 'Brief and blunt, sometimes rudely so.', 'A terse reply can read as rude even when it is not meant to be.'),
('Timorous', 'adjective', 'Nervous and lacking courage.', 'A timorous start to a speech usually settles after a line or two.'),
('Torpid', 'adjective', 'Mentally or physically inactive.', 'A heavy lunch can leave the whole class torpid.'),
('Tractable', 'adjective', 'Easy to manage or deal with.', 'Break a large syllabus into tractable weekly chunks.'),
('Transcend', 'verb', 'To go beyond usual limits.', 'A great project transcends the marking scheme and teaches you something.'),
('Trepidation', 'noun', 'A feeling of fear about what may happen.', 'She opened the result email with real trepidation.'),
('Truncate', 'verb', 'To shorten by cutting off part.', 'The timer forced him to truncate his conclusion.'),
('Umbrage', 'noun', 'Offence or annoyance.', 'He took umbrage at the suggestion that he had not tried.'),
('Unassuming', 'adjective', 'Modest; not seeking attention.', 'The unassuming student turned out to have topped the district.'),
('Uncanny', 'adjective', 'Strange in an unsettling way.', 'She had an uncanny knack for guessing which questions would appear.'),
('Unequivocal', 'adjective', 'Leaving no doubt.', 'The rubric was unequivocal about needing a labelled diagram.'),
('Unprecedented', 'adjective', 'Never done or known before.', 'The number of students taking the coding elective was unprecedented.'),
('Unscrupulous', 'adjective', 'Without moral principles.', 'An unscrupulous shortcut usually costs more than it saves.'),
('Untenable', 'adjective', 'Not able to be defended.', 'Once the data came in, his theory was untenable.'),
('Vacillate', 'verb', 'To keep changing your mind.', 'If you vacillate on every question, you run out of time.'),
('Vehement', 'adjective', 'Showing strong, forceful feeling.', 'She was vehement that the group would not skip the checking step.'),
('Venerable', 'adjective', 'Respected for age, wisdom, or character.', 'The venerable library has been the quiet heart of the school for decades.'),
('Verbatim', 'adverb', 'In exactly the same words.', 'Copying a definition verbatim without understanding it shows in the next question.'),
('Vicarious', 'adjective', 'Felt through another person rather than directly.', 'She got a vicarious thrill from a friend getting an acceptance letter.'),
('Vindicate', 'verb', 'To clear of blame or prove right.', 'The final result vindicated her decision to change methods.'),
('Vivacious', 'adjective', 'Lively and full of energy.', 'A vivacious host kept the science fair from feeling flat.'),
('Vociferous', 'adjective', 'Loud and forceful in expressing opinions.', 'A vociferous minority is not the same as a majority.'),
('Voracious', 'adjective', 'Wanting a great deal of something, especially knowledge.', 'A voracious reader walks into English exams calm.'),
('Wane', 'verb', 'To decrease in strength or size.', 'Motivation will wane, so lean on a schedule instead.'),
('Wary', 'adjective', 'Cautious about possible danger.', 'Be wary of notes that promise to cover everything in an hour.'),
('Whimsical', 'adjective', 'Playfully unusual.', 'A whimsical example can make a dry concept stick.'),
('Wield', 'verb', 'To hold and use power or a tool effectively.', 'A student who can wield a clear diagram saves paragraphs of writing.'),
('Wistful', 'adjective', 'Full of gentle, sad longing.', 'Seniors get wistful walking past their old classrooms.'),
('Wry', 'adjective', 'Dryly and cleverly humorous.', 'A wry aside from the teacher kept the long lecture awake.'),
('Zenith', 'noun', 'The highest point.', 'Her confidence hit its zenith right after the mock results.'),
('Abhor', 'verb', 'To hate strongly.', 'She abhors leaving a question half-answered.'),
('Acquiesce', 'verb', 'To accept something reluctantly, without protest.', 'He acquiesced to the group topic even though he preferred another.'),
('Acumen', 'noun', 'The ability to make good judgements quickly.', 'Her business acumen showed in how she priced the fundraiser.'),
('Admonish', 'verb', 'To warn or scold gently but firmly.', 'The teacher admonished the class for skipping the reading.'),
('Affinity', 'noun', 'A natural liking or connection.', 'She has an affinity for problems that look impossible at first.'),
('Allude', 'verb', 'To refer to something indirectly.', 'The question alluded to a chapter that was not on the list.'),
('Amass', 'verb', 'To gather a large amount over time.', 'He amassed a folder of solved problems across the year.'),
('Ardent', 'adjective', 'Very enthusiastic or passionate.', 'An ardent reader rarely fears the unseen passage.'),
('Belittle', 'verb', 'To make someone or something seem unimportant.', 'Do not belittle a small daily habit; it compounds.'),
('Berate', 'verb', 'To scold angrily and at length.', 'Berating yourself after a mistake wastes the time you could spend fixing it.'),
('Chastise', 'verb', 'To criticise or punish sharply.', 'He was chastised for handing in a rushed lab report.'),
('Culminate', 'verb', 'To reach a final point or result.', 'Weeks of practice culminated in a calm, clean final paper.'),
('Deleterious', 'adjective', 'Causing harm or damage.', 'A deleterious habit of last-minute cramming hurt her retention.'),
('Efface', 'verb', 'To rub out or make disappear.', 'Time did not efface the lesson from that failed first attempt.'),
('Elated', 'adjective', 'Extremely happy and excited.', 'She was elated to see her name on the merit list.'),
('Embellish', 'verb', 'To add extra, often untrue, detail.', 'Do not embellish your project results; examiners check.'),
('Equivocate', 'verb', 'To use vague language to avoid committing to a view.', 'A good answer takes a position instead of equivocating.'),
('Extol', 'verb', 'To praise highly.', 'The report extols the method without mentioning its one flaw.'),
('Fickle', 'adjective', 'Changing loyalty or interest often.', 'Attention is fickle, so make your first sentence count.'),
('Gauche', 'adjective', 'Socially awkward or tactless.', 'It felt gauche to ask the marks of a classmate who did badly.'),
('Impute', 'verb', 'To attribute a fault or quality to someone.', 'Do not impute laziness to a teammate who was simply unwell.'),
('Nascent', 'adjective', 'Just beginning to develop.', 'Her nascent interest in economics grew into her degree choice.'),
('Obstinate', 'adjective', 'Stubbornly refusing to change.', 'Being obstinate about one method can blind you to a faster one.'),
('Pervasive', 'adjective', 'Spreading widely throughout something.', 'The fear of one hard subject can become pervasive if you let it.'),
('Rescission', 'noun', 'The act of cancelling something officially.', 'The rescission of the late penalty came after a fair appeal.'),
('Trite', 'adjective', 'Overused and lacking freshness.', 'A trite conclusion makes a sharp essay end weakly.'),
('Vestige', 'noun', 'A small remaining trace of something.', 'By June there was not a vestige of her early-year nerves.'),
('Wanton', 'adjective', 'Deliberate and unprovoked; careless of consequences.', 'Wanton guessing on a negative-marking paper is expensive.'),
('Zealotry', 'noun', 'Extreme and uncompromising commitment to a cause.', 'Studying hard is good; zealotry that skips sleep is not.');
