"use client";

import { useRef, useState, useSyncExternalStore } from "react";
import { Sparkles, Volume2 } from "lucide-react";
import type { VocabularyWord } from "@/lib/types/database";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScratchCard } from "@/components/scratch-card";
import { cn } from "@/lib/utils";

function storageKeyFor(wordId: string) {
  return `wotd-revealed-${wordId}`;
}

// getServerSnapshot fixed at false (matches components/theme-toggle.tsx's
// own reasoning): localStorage doesn't exist during SSR, and this must
// match the client's very first hydration pass exactly or React flags a
// mismatch. The client re-renders with the real value immediately after
// hydration — a word already scratched open earlier today shows its
// content correctly with, at most, one imperceptible extra render.
function subscribe() {
  return () => {};
}
function getServerSnapshot() {
  return false;
}

/**
 * The "learn" half of the vocabulary feature — pure reading, no scoring.
 * The word and a pronunciation button are always visible ("hear it
 * before you're quizzed"); the meaning underneath is a scratch card (see
 * components/scratch-card.tsx) — a user's own suggestion, doing this felt
 * more like a genuine reveal than a plain tap-to-expand ever did. Once
 * scratched open, it stays open until the next calendar day's word swaps
 * in a new `word.id`, at which point the localStorage key for the new id
 * simply doesn't exist yet — no date bookkeeping needed, the daily swap
 * itself is what "resets" it. Audio is a British-female clip generated by
 * Amazon Polly (scripts/generate-word-audio.mjs) and served from our own
 * Storage — a row with no `audio_url` yet just shows no speaker button.
 */
export function WordOfTheDay({ word }: { word: VocabularyWord }) {
  const storageKey = storageKeyFor(word.id);
  const alreadyRevealed = useSyncExternalStore(
    subscribe,
    () => localStorage.getItem(storageKey) === "1",
    getServerSnapshot,
  );
  // Separate from alreadyRevealed: this is *this session's own* fresh
  // scratch, which is what should get the celebratory bump — reopening a
  // word you already revealed earlier today shouldn't replay it.
  const [justScratched, setJustScratched] = useState(false);
  const [playing, setPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);

  const revealed = alreadyRevealed || justScratched;

  function handleReveal() {
    localStorage.setItem(storageKey, "1");
    setJustScratched(true);
  }

  function playPronunciation() {
    const audio = audioRef.current;
    if (!audio) return;
    audio.currentTime = 0;
    // .play() rejects on iOS in some states — swallow it so the click just
    // doesn't animate, rather than throwing an unhandled rejection.
    audio
      .play()
      .then(() => setPlaying(true))
      .catch(() => setPlaying(false));
  }

  return (
    <Card className="overflow-hidden p-0">
      <div className="flex flex-col items-center gap-2 px-6 pb-5 pt-8 text-center">
        <span className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          <Sparkles className="h-3.5 w-3.5" />
          Word of the Day
        </span>

        <div className="flex items-center gap-2.5">
          <span
            className={cn(
              "brand-gradient-text text-3xl font-extrabold",
              justScratched && "animate-wotd-bump",
            )}
          >
            {word.word}
          </span>
          {word.audio_url && (
            <button
              type="button"
              onClick={playPronunciation}
              aria-label={`Hear ${word.word} pronounced`}
              className={cn(
                "flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-border text-muted-foreground transition-transform hover:bg-muted active:scale-90",
                playing && "bg-muted text-foreground",
              )}
            >
              <Volume2 className="h-4 w-4" />
            </button>
          )}
        </div>

        {word.audio_url && (
          <audio
            ref={audioRef}
            src={word.audio_url}
            preload="auto"
            className="hidden"
            onEnded={() => setPlaying(false)}
            onPause={() => setPlaying(false)}
          />
        )}
      </div>

      <ScratchCard revealed={revealed} onReveal={handleReveal} label="Scratch to reveal">
        <div className="space-y-2 border-t border-border px-6 py-4">
          <Badge variant="accent" className={cn(justScratched && "animate-wotd-reveal")}>
            {word.part_of_speech}
          </Badge>
          <p
            className={cn("text-sm font-medium text-foreground", justScratched && "animate-wotd-reveal")}
            style={justScratched ? { animationDelay: "60ms" } : undefined}
          >
            {word.definition}
          </p>
          <p
            className={cn(
              "text-sm italic text-muted-foreground",
              justScratched && "animate-wotd-reveal",
            )}
            style={justScratched ? { animationDelay: "120ms" } : undefined}
          >
            &ldquo;{word.example_sentence}&rdquo;
          </p>
        </div>
      </ScratchCard>
    </Card>
  );
}
