"use client";

import { useRef, useState } from "react";
import { Sparkles, Volume2 } from "lucide-react";
import type { VocabularyWord } from "@/lib/types/database";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

/**
 * The "learn" half of the vocabulary feature — pure reading, no scoring.
 * The word and a pronunciation button are always visible ("hear it
 * before you're quizzed"); tapping the strip below springs the
 * definition and example open, one line at a time. Audio is
 * a British-female clip generated by Amazon Polly
 * (scripts/generate-word-audio.mjs) and served from our own Storage — a
 * row with no `audio_url` yet just shows no speaker button.
 */
export function WordOfTheDay({ word }: { word: VocabularyWord }) {
  const [revealed, setRevealed] = useState(false);
  const [playing, setPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);

  function playPronunciation() {
    const audio = audioRef.current;
    if (!audio) return;
    audio.currentTime = 0;
    // .play() rejects on iOS in some states — swallow it so the click just
    // doesn't animate, rather than throwing an unhandled rejection.
    audio
      .play()
      .then(() => setPlaying(true))
      .catch(() => setPlaying(false));
  }

  return (
    <Card className="overflow-hidden p-0">
      <div className="flex flex-col items-center gap-2 px-6 pb-5 pt-8 text-center">
        <span className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          <Sparkles className="h-3.5 w-3.5" />
          Word of the Day
        </span>

        <div className="flex items-center gap-2.5">
          <span
            className={cn(
              "brand-gradient-text text-3xl font-extrabold",
              revealed && "animate-wotd-bump",
            )}
          >
            {word.word}
          </span>
          {word.audio_url && (
            <button
              type="button"
              onClick={playPronunciation}
              aria-label={`Hear ${word.word} pronounced`}
              className={cn(
                "flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-border text-muted-foreground transition-transform hover:bg-muted active:scale-90",
                playing && "bg-muted text-foreground",
              )}
            >
              <Volume2 className="h-4 w-4" />
            </button>
          )}
        </div>

        {word.audio_url && (
          <audio
            ref={audioRef}
            src={word.audio_url}
            preload="auto"
            className="hidden"
            onEnded={() => setPlaying(false)}
            onPause={() => setPlaying(false)}
          />
        )}
      </div>

      {!revealed ? (
        <button
          type="button"
          onClick={() => setRevealed(true)}
          className="w-full border-t border-border px-6 py-3 text-xs text-muted-foreground transition-transform duration-100 hover:bg-muted/50 active:scale-[0.98]"
        >
          Tap to reveal meaning
        </button>
      ) : (
        <div className="space-y-2 border-t border-border px-6 py-4">
          <Badge variant="accent" className="animate-wotd-reveal">
            {word.part_of_speech}
          </Badge>
          <p
            className="animate-wotd-reveal text-sm font-medium text-foreground"
            style={{ animationDelay: "60ms" }}
          >
            {word.definition}
          </p>
          <p
            className="animate-wotd-reveal text-sm italic text-muted-foreground"
            style={{ animationDelay: "120ms" }}
          >
            &ldquo;{word.example_sentence}&rdquo;
          </p>
        </div>
      )}
    </Card>
  );
}
